### ISSUE TITLE
Servo Motors Overheat

### ISSUE THREAD

**Issue by WilliamWalkerMercier** [adeept/adeept_picar-b#13]
I use this robot for a school project, but my servomotors after like 2 mins of use are extremely hot ? Is the problem software or hardware? Is there anything i can do because i've already changed one servomotor.

Cordially

**Comment by adeept** [comment]
Hello,
Is the replacement servo also experiencing the same heating phenomenon?
Recently we updated the maximum PWM value of the servo, changing 560 to 520.
You can back up your existing product code folder and download the code again.
Or change lines 53 and 57 in the server/RPIservo.py program. Change 560 to 520. (See the modification record on github)


 Technical Support
 ***@***.***
  



---- Replied Message ----
From  William ***@***.***> Date  7/28/2023 22:39 To  ***@***.***> Cc  ***@***.***> Subject  [adeept/adeept_picar-b] Servo Motors Overheat (Issue #13)  

I use this robot for a school project, but my servomotors after like 2 mins of use are extremely hot ? Is the problem software or hardware? Is there anything i can do because i've already changed one servomotor.
Cordially

**Comment by WilliamWalkerMercier** [comment]
Thanks for your fast answer 
The replacement servo don't have the same heating phenomenon. When i launch webServer.py , i don't use the head servos for example but they start to heat and the replacement one doesn't (it's the front one that directs the robot) .

Cordially

**Comment by adeept** [comment]
Hello,
If the replacement steering gear does not heat up, it should be caused by the failure of the steering gear. If there are other servos in the product that you are using that have overheating, please contact us by email.
E-mail: ***@***.***


 Technical Support
 ***@***.***
  



---- Replied Message ----
From  William ***@***.***> Date  7/30/2023 21:02 To  ***@***.***> Cc  ***@***.***> ,
 ***@***.***> Subject  Re: [adeept/adeept_picar-b] Servo Motors Overheat (Issue #13)  

replacement servo don't have the same heating phenomenon. When i launch webServer.py , i don't use the head servos for example but they start to heat and the replacement one doesn't (it's the front one that directs the robot)
